### ISSUE TITLE
Creating an account should make checks on the backend

### ISSUE THREAD

**Issue by darwinfroese** [darwinfroese/hacksite#1]
*Please look at the contributing document or wiki page prior to contributing!*

## Summary
The message should be returned in the response as to why account creation failed and echoed to the user via the UI.

## Details
* [x] Check if an username is in use
* [x] Check if an email is in use

**Comment by The-Outrider** [comment]
I'll take a crack at this one. I've got the code all setup now. :)

**Comment by darwinfroese** [comment]
Awesome! Thanks @The-Outrider. You may be out of sync -- i had to make a bunch of commits to get CI and CD set up!

**Comment by The-Outrider** [comment]
Totally up to date, I saw all the commits you made yesterday and rebased my fork accordingly 👍
