### ISSUE TITLE
Database should be a singleton

### ISSUE THREAD

**Issue by darwinfroese** [darwinfroese/hacksite#11]
CreateDB should return a pointer to the database (if the pointer is nil) and return the pointer otherwise. All current calls to `CreateDB` will need to be updated and should be renamed to `GetDB`.

**Comment by blockloop** [comment]
I'll look into this

**Comment by blockloop** [comment]
You want `GetDB` to return a pointer to a database, but where do you want the database set?

**Comment by blockloop** [comment]
A package level variable (not recommended)?

**Comment by darwinfroese** [comment]
Ya, global variables are never recommended.

I was thinking something more along the lines of:

database.go
```go
var db *Database

func GetDB() *Database {
    // init or return db
}
```

and then every package would call `database.GetDB` instead of calling `CreateDB` once in main and passing that same database around to handler and package which _should_ result in less coupling.

**Comment by blockloop** [comment]
Hmm. Perhaps I am not following what you mean. Seems like a bad idea to me. However, when I look at the code I see you're passing an interfaced Database into your `apiContext`. Creating the db connection in `main.go` and passing it to a handlers is common practice in my experience. Maybe you can help me by explaining the problem you want to solve.

**Comment by darwinfroese** [comment]
I do agree that the context is common practice, but I've also seen a lot of people creating the pointer and just returning that on calls to a function similar to `GetDB` -- a lot of which i think is people coming from C#/Java backgrounds where this is a very common practice.

My main concern is every package (accounts, tasks, etc.) are all receiving a number of dependencies (currently session and database) which then ties them to those packages.

**Comment by blockloop** [comment]
It's certainly commonplace in C# world (I have 10 years experience with C#), but it's something that I grew to stay away from. I would recommend keeping what you have with injected dependencies as interfaces. I won't tell you how to write your project though. If a package variable is what you wish then consider it done.

P.S. [here is a good writeup](https://dave.cheney.net/2017/06/11/go-without-package-scoped-variables) by Dave Cheney on this kind of behavior.

**Comment by darwinfroese** [comment]
Ya, I agree. I've been reading a few articles and think it will end up working out better. I'm going to close this issue as a result.

Thanks for the input and advice @blockloop!
