### ISSUE TITLE
Implement RememberMe functionality

### ISSUE THREAD

**Issue by darwinfroese** [darwinfroese/hacksite#15]
*Please look at the contributing document or wiki page prior to contributing!*

## Summary
A nice to have that prevents the user from having to re-login all the time.

## Details
* [x] Checkbox on login that says "remember me"
* [x] A flag in the login account model for if the user has selected remember me
* [x] Set max-age of the cookie to 0 (never expires)
* [x] Add a flag to the session to see if it should expire
    * make sure to update the remove session database function to check if it's expired and if it should be removed

**Comment by The-Outrider** [comment]
I'll tackle this one as well.
