### ISSUE TITLE
Completing an evolution behaviour

### ISSUE THREAD

**Issue by darwinfroese** [darwinfroese/hacksite#18]
*Please look at the contributing document or wiki page prior to contributing!*

## Summary
After completing an evolution it should prompt to create a new evolution if none exist after the current one. If there is another evolution, it should move to that one automatically.

## Details
The endpoint on the server (`updateTask`) should check that if all the tasks in the evolution have been completed, move to the next evolution if one exists, otherwise just return like normal which will prompt the modal.

**Comment by lccezinha** [comment]
Hey @darwinfroese I'll try to fix this ok ?

**Comment by lccezinha** [comment]
Hey @darwinfroese I sent you an email with some doubts, can you check it please ?
