### ISSUE TITLE
Deleting a project should prompt

### ISSUE THREAD

**Issue by darwinfroese** [darwinfroese/hacksite#19]
*Please look at the contributing document or wiki page prior to contributing!*

## Summary
Allow the user to confirm that they want to delete the project or not.

## Details
* [x] Create an element for the prompt modal that can be re-used for other prompts
* [x] Prompt when the delete button is clicked and call the server endpoint if the user confirms

**Comment by CodeB9** [comment]
@darwinfroese I'm working on this 😉

**Comment by darwinfroese** [comment]
completed!
