### ISSUE TITLE
Account settings page

### ISSUE THREAD

**Issue by darwinfroese** [darwinfroese/hacksite#20]
*Please look at the contributing document or wiki page prior to contributing!*

## Summary 

It would be nice to have an account settings page to change things like:

* account information
* password
* email

## Details
Need to implement the following

* [ ] Account update endpoint ( #41 )
* [ ] New view for account settings ( #42  )
* [ ] Link to the new view from the title header
    * [ ] Add a link in the header bar next to `logout` for `account`
    * [ ] `Account` link should route to the new View
* [ ] Update javascript database to call `account` with `GET` and `PUT` with the data to update the accoun

**Comment by ins0** [comment]
i will give it a try

**Comment by darwinfroese** [comment]
This will be covered in the `Hacksite Rebranding` project.
