### ISSUE TITLE
Remove context from handlers.

### ISSUE THREAD

**Issue by darwinfroese** [darwinfroese/hacksite#36]
Remove the `context` struct and remove `context` references from the code returning all HttpHandlers to standard HttpHandlers instead of context handlers.

**Comment by blockloop** [comment]
I can offer you a pattern that I generally use here if you're still interested in this.

**Comment by darwinfroese** [comment]
Sure.

My main concern is the packages for `accounts` and `tasks` being tied highly to `database` and `session` with receiving those parameters on each function call in those packages.

**Comment by blockloop** [comment]
Here's how I normally do it.

```
// api_server.go
type apiServer struct {
    db database.Database // interface
}

func (s *apiServer) GetProjects(w http.ResponseWriter, r *http.Request) {
   // use s.db and write http response
}

func (s *apiServer) PostProject(w http.ResponseWriter, r *http.Request) {
   // use s.db and write http response
}

func (s *apiServer) PutProject(w http.ResponseWriter, r *http.Request) {
   // use s.db and write http response
}
```


```
// main.go 

func main() {
    db := database.CreateDB()
    server := &apiServer{db: db}
    httpServer := registerRoutes(server)
    httpServer.ServeHTTP()
}

func registerRoutes(s *apiServer) http.Handler {

}
```

**Comment by darwinfroese** [comment]
I think this still has the same issue with the `projects` et al packages all relying on `database` and `session`. The only way to remove these dependencies may to be to just make `context` the common point and send the `context` into the subpackages and let them use the DB value from there.

**Comment by darwinfroese** [comment]
If you wrap it in context the `project` package would only rely on the `context` package. The `context` package would then rely on the `database` package.

You can then swap `database` packages in the `context` package and it has no impact on the `project` package. If it's a dependency i feel it's a much looser dependency.

**Comment by blockloop** [comment]
Okay so the `context` package will have an interface for the db actions? i.e. `context.ListPackages` or will the `project` package simply call `context.DB.Update`?

**Comment by darwinfroese** [comment]
the later.

**Comment by darwinfroese** [comment]
I think I'm going to close this issue and create a new one to handle passing the context down into the sub packages instead of removing it.
