### ISSUE TITLE
Account Endpoint

### ISSUE THREAD

**Issue by darwinfroese** [darwinfroese/hacksite#41]
_Please look at the contributing document or wiki page prior to contributing!_

## Summary

Update the `account` api endpoint to handle Updating and Viewing an account.

## Details

* GET *
- [x] Use `GetAccountByUsername` and the `Username` value from the session to get the user settings from the DB
- [x] Send back `{ Username, Email }`
- [x] Map `ViewAccount` function to `GET` method for the `accounts` route (similar to how Projects has a map)

* UPDATE *
- [x] Use `GetAccountByUsername` and the `Username` value from the session to get the user settings from the DB
- [x] Update the fields `{ Username, Email, Password }` with the values sent by the client
- [x] Map `UpdateAccount` function to `PATCH` and `PUT` methods for the `accounts` route

**Comment by ins0** [comment]
i will give it a try
