### ISSUE TITLE
Enter key should trigger buttons

### ISSUE THREAD

**Issue by darwinfroese** [darwinfroese/hacksite#45]
_Please look at the contributing document or wiki page prior to contributing!_

## Summary

Want to be able to use keyboard to fill in forms and use the enter key to send data.

## Details

On all forms/views with a primary button, if the button can be clicked and the user presses the enter key, the button should be "clicked".

**Comment by PriyankaGitHub7** [comment]
@darwinfroese I have started working on this.

**Comment by PriyankaGitHub7** [comment]
@darwinfroese Raised the pull request #54 for this.
