### ISSUE TITLE
Move validation server side

### ISSUE THREAD

**Issue by darwinfroese** [darwinfroese/hacksite#49]
## Summary

Moving validation server-side allows simple development of new clients.

## Details

Move all creation validation (project, iteration, user) server-side so. Client-side can remain and can be used as a "fail fast" validation.

* Create Account Validation
    * [ ] username is alpha-numeric and longer than 3 characters
    * [ ] email is a valid email ( check for `@` with a `.` after)
* Project Validation
    * [ ] project name isn't empty

**Comment by alimasyhur** [comment]
[commited](https://github.com/darwinfroese/hacksite/pull/58)

**Comment by darwinfroese** [comment]
Some changes will be required as a result of this, documented in: #63
