### ISSUE TITLE
Update  release notes for Beta Release

### ISSUE THREAD

**Issue by darwinfroese** [darwinfroese/hacksite#59]
Add all of the release notes from [here](https://github.com/darwinfroese/hacksite/wiki/beta_0.5) once all of the beta work is completed.

Depends on all beta work being completed.

**Comment by saideepd** [comment]
I would like to contribute to Update Release Notes for Beta Release.
How should I write the Release Notes? By uploading an external Release Notes file or some other way?

**Comment by darwinfroese** [comment]
Currently they are just manually added and I'm looking into a way to automate it in the future.

There is currently a file [here](https://github.com/darwinfroese/hacksite/blob/master/webclient/src/components/views/ReleaseNotes.vue) that has most of them already listed. They just need to be updated to match what's currently in wiki page. It should also have the 3 issues that are in progress [#18](https://github.com/darwinfroese/hacksite/issues/18), [#15](https://github.com/darwinfroese/hacksite/issues/15), and [#30](https://github.com/darwinfroese/hacksite/issues/18) added to just the `.vue` component (15 and 30 are "new features" and 18 is a "bugfix") and we'll merge the PR when those 3 are actually completed and update the wiki page.

**Comment by saideepd** [comment]
I'll try to see if I can do anything to automate the release notes.
Till then should I add the 2 new features and a bug fix to current release notes and make a PR ?

**Comment by darwinfroese** [comment]
@saideepd I wouldn't worry about automating it right now. It's going to need some changes to the delivery pipeline which only I have access to.

It's going to need the 2 features and the 1 bug fix in the PR as well as:

- The restructuring into different sections like in the wiki
- The entries that aren't in the component right now.

**Comment by saideepd** [comment]
OK

**Comment by darwinfroese** [comment]
@saideep

I'm going to move this issue back to the `Todo` status so that someone else can complete the work.
